// Code generated by mockery v1.0.0
package mocktransport

import dispatcher "github.com/projectriff/function-sidecar/pkg/dispatcher"
import mock "github.com/stretchr/testify/mock"

// Consumer is an autogenerated mock type for the Consumer type
type Consumer struct {
	mock.Mock
}

// Messages provides a mock function with given fields:
func (_m *Consumer) Messages() <-chan dispatcher.Message {
	ret := _m.Called()

	var r0 <-chan dispatcher.Message
	if rf, ok := ret.Get(0).(func() <-chan dispatcher.Message); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan dispatcher.Message)
		}
	}

	return r0
}
